drop table if exists AccessCountEntity CASCADE;
drop table if exists MemberEntity CASCADE;

create table AccessCountEntity (
   id bigint generated by default as identity,
    ipAddr varchar(255),
    dayCount integer not null,
    monthCount integer not null,
    totalCount integer not null,
    yearCount integer not null,
    createdAt timestamp,
    updatedAt timestamp,
    primary key (id)
);
alter table AccessCountEntity
   add constraint UK_AccessCountEntity_ipAddr unique (ipAddr);

create table MemberEntity (
   id bigint generated by default as identity,
    email varchar(50) not null,
    password varchar(50) not null,
    nickName varchar(50) not null,
    role varchar(5) not null,
    age integer,
    phoneNumber varchar(50),
    zipcode varchar(6),
    address varchar(50),
    addressDetail varchar(100),
    createdAt timestamp not null,
    updatedAt timestamp not null,
    primary key (id)
);
alter table MemberEntity
   add constraint UK_MemberEntity_email unique (email);

